language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
addons:
  apt:
    packages:
      - libsdl2-dev
      - libasound2-dev
      - libfreetype6-dev
