language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
addons:
  apt:
    packages:
      - libsdl2-dev
      - libasound2-dev
      - libsdl2-ttf-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
