[package]
name = "j2gbc"
version = "0.1.0"
authors = ["Jennifer Wilcox <jennifer@nitori.nl>"]

[dependencies]
log = "*"
lazy_static = "*"
cpal = "*"
rb = "*"
hound = "*"

[dependencies.sdl2]
version = "*"
features = ["ttf"]

[dependencies.j2ds]
path = "../j2ds"
