[package]
name = "minifb_frontend"
version = "0.1.0"
authors = ["Jennifer Wilcox <jennifer@nitori.org>"]
edition = "2018"

[dependencies]
j2gbc = { path = "../j2gbc" }
frontend_utils = { path = "../frontend_utils" }
cpal_audio = { path = "../cpal_audio" }
minifb = "0.19.3"
clap = "^2.33.0"