[package]
name = "j2gbc_sdl"
version = "0.1.0"
authors = ["Jennifer Wilcox <jennifer@nitori.nl>"]

[dependencies]
log = "*"
lazy_static = "*"
cpal = "*"
rb = "*"
hound = "*"
j2gbc = { path = "../j2gbc" }

[dependencies.sdl2]
version = "*"
features = ["ttf"]

[dependencies.j2ds]
version = "*"
