on: push
name: CI Tests
jobs:
  ci:
    name: CI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: "git submodule update --init --recursive"
      - uses: Nitori-/rust-actions/get-rust@master
      - run: "sudo apt-get install -y libasound-dev libgtk-3-dev"
      - run: "make -C j2gbc/gb-conformance"
      - run: "cargo fmt -- --check"
      - run: "cargo clippy -- -Dwarnings"
      - run: "cargo test"
