on: push
name: CI Tests
jobs:
  ci:
    name: CI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: Nitori-/rust-actions/get-rust@master
        with:
          version: stable
          make_default: true
          components: "rustfmt"
      - run: "sudo apt-get install -y libasound-dev libgtk-3-dev"
      - run: "cargo fmt -- --check"
      - run: "cargo test"
        env:
          RUST_BACKTRACE: 1
