on: push
name: CI Tests
jobs:
  ci:
    name: CI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: ./.github/actions/ci
